version: '3'

# #####################################################################################
# IMPORTANT:
# Use `docker-compose up -d --scale redis-sentinel=3` to make sentinels fault tolerant!
# #####################################################################################

# For development / testing purposes only. Production would obviously have a different
# networking and application clustering setup.

# This compose file is meant to be a part of a bigger compose file that contains the
# actual application containers, so all of them are on the same netwwork.

services:

  redis-master:
    image: 'redis:4.0-alpine'
    volumes:
      -   redis-master-data:/data # Named volume, survives container death
      # - "./.data-master:/data"  # Causes issues on my Windows notebook, not able to sync file, the error keeps repeating:
                                  # Failed trying to rename the temp DB into dump.rdb in MASTER <-> SLAVE synchronization: Text file busy
    command: 'redis-server --databases 1 --save 60 1 --appendonly yes --appendfsync everysec'

  redis-slave:
    image: 'redis:4.0-alpine'
    volumes:
      -   redis-slave-data:/data # Named volume, survives container death
      # - "./.data-slave:/data"  # Causes issues on my Windows notebook, not able to sync file, the error keeps repeating:
                                 # Failed trying to rename the temp DB into dump.rdb in MASTER <-> SLAVE synchronization: Text file busy
    command: 'redis-server --databases 1 --save 60 1 --appendonly yes --appendfsync everysec --slaveof redis-master 6379'

  redis-sentinel:
    build:
      context: ./sentinel
    image: 'tkarakai-gto/redis-sentinel:latest'
    environment:
      - SENTINEL_MONITOR_HOST=redis-master
      - SENTINEL_MONITOR_PORT=6379
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    depends_on:
      - redis-master
      - redis-slave

# Named volumes
volumes:
  redis-master-data:
  redis-slave-data:
